steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia.gcr.io/mashup-dev-project-267408/language-pack-default', '.' ]
images:
  - 'asia.gcr.io/mashup-dev-project-267408/language-pack-default'